modLoader = "javafml"
loaderVersion = "*"
license = "LGPLv3"
issueTrackerURL="https://gitea.codersquack.nl/NeoFlock/NeoComputers/issues"

[[mods]]
modId = "neocomputers"
version = "${version}"
displayName = "${name}"
authors = "NeoFlock Team"
description = ""
logoFile = "assets/neocomputers/icon.png"
logoBlur = false

[[mixins]]
config = "neocomputers-common.mixins.json"

[[mixins]]
config = "neocomputers-neoforge.mixins.json"